[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "Noto Sans Mono"
style = "Bold"

[font.bold_italic]
family = "Noto Sans Mono"
style = "Bold Italic"

[font.italic]
family = "Noto Sans Mono"
style = "Italic"

[font.normal]
family = "Noto Sans Mono"
style = "Regular"

[window]
opacity = 1
padding = { x = 6, y = 2 }
blur = false

[colors.primary]
background = "#222222"
foreground = "#bbbbbb"
bright_foreground = "#eeeeee"
dim_foreground = "#bbbbbb"

[colors.cursor]
text = "#222222"
cursor = "#eeeeee"

[colors.selection]
text = "#222222"
background = "#444444"

[colors.normal]
black = "#222222"
red = "#cc6666"
green = "#88b090"
yellow = "#d0a36b"
blue = "#005577"
magenta = "#cc6666"
cyan = "#88b090"
white = "#bbbbbb"

[colors.bright]
black = "#444444"
red = "#cc6666"
green = "#88b090"
yellow = "#d0a36b"
blue = "#005577"
magenta = "#d0a36b"
cyan = "#88b090"
white = "#eeeeee"
